"""language dropped

Revision ID: 2bf6f95d2d30
Revises: 2e1c0a114d42
Create Date: 2026-03-22 18:50:30.170599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf6f95d2d30'
down_revision: Union[str, Sequence[str], None] = '2e1c0a114d42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('language', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
